import React from "react";
import "./CreatedPages.css";
import { Link } from "react-router-dom";

/**
 * This function displays all the pages generated by the user using the minimongo storage
 * @param {page} props Pages stored in the minimongo
 * @returns All the pages created by the user
 */
function CreatedPages(props) {
  let urlElements = window.location.href;

  return (
    <div className="CreatedPages">
      {props.pages?.map((page, index) => {
        return (
          <div className="iframeDiv" key={"iframeDiv" + index}>
            <iframe
              title={"iframe" + index}
              className="iframe"
              src={urlElements + "/user_home_page:" + page.url}
              width="600px"
              height="300px"
            ></iframe>
            <div className="RefLink">
              <Link to={"/homepage_creator/user_home_page:" + page.url}>
                Link to : {page.url}
              </Link>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default CreatedPages;
